name: Reachability

on: repository_dispatch
  
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      URL: ${{ github.event.client_payload.url || 'https://api.github.com' }} 
    steps:
    - name: Check ${{ URL }} 
      run: curl -vL $URL
